export const CATALOG = {
  house: {
    name: "Cottage",
    size: 3,
    cost: { wood: 30, stone: 10 },
    description: "A warm hearth and room for two more workers.",
    effect: "+2 housing capacity · houses 2 workers (simulation limit 24)",
    seconds: 12,
  },
  well: {
    name: "Well",
    size: 2,
    cost: { wood: 15, stone: 25 },
    description: "Fresh water at the heart of your growing settlement.",
    effect: "A gathering place for your village",
    seconds: 10,
  },
  farm: {
    name: "Farmhouse",
    size: 4,
    cost: { wood: 25, stone: 5 },
    description: "The home base for farmers who tend connected grain fields.",
    effect: "Harvests ripe connected grain fields · +8 wheat per plot",
    resource: "wheat",
    amount: 8,
    seconds: 14,
    upgrade: {
      name: "Rich soil",
      cost: { wood: 35, stone: 12 },
      effect: "+4 wheat per harvest",
    },
  },
  bakery: {
    name: "Bakery",
    size: 3,
    cost: { wood: 40, stone: 25 },
    description: "A wood-fired oven turns farm wheat into fresh bread for the village.",
    effect: "4 wheat → 8 bread (food) per cycle · 16 seconds",
    resource: "food",
    amount: 8,
    input: 4,
    inputResource: "wheat",
    seconds: 16,
  },
  inn: {
    name: "Inn",
    size: 4,
    cost: { wood: 55, stone: 25 },
    description: "A welcoming table where hungry villagers share fresh bread.",
    effect: "Receives bread from bakeries · seats 3 hungry workers",
    seconds: 18,
  },
  grainfield: {
    name: "Grain field",
    size: 1,
    cost: { food: 1 },
    description: "Plant beside a farmhouse, then extend the field one tile at a time.",
    effect: "Grows in 30 seconds · farmers harvest it automatically",
    seconds: 0,
    decoration: true,
    tileTool: true,
  },
  lumberyard: {
    name: "Lumberyard",
    size: 3,
    cost: { wood: 20, stone: 10 },
    description: "Workers fell nearby trees, then saw the logs into wooden planks.",
    effect: "+8 wooden planks per delivery · trees regrow over time",
    resource: "wood",
    amount: 8,
    seconds: 12,
  },
  mine: {
    name: "Stone mine",
    size: 4,
    cost: { wood: 35, stone: 15 },
    description: "A steady source of stone from beneath the hills.",
    effect: "+6 stone per delivery",
    resource: "stone",
    amount: 6,
    seconds: 18,
  },
  windmill: {
    name: "Windmill",
    size: 4,
    cost: { wood: 50, stone: 35 },
    description: "Grinds the harvest into flour. Requires food to work.",
    effect: "2 food → 8 food per cycle",
    resource: "food",
    amount: 8,
    input: 2,
    seconds: 20,
    upgrade: {
      name: "Faster sails",
      cost: { wood: 45, stone: 20 },
      effect: "Cycles 25% faster",
    },
  },
  watchtower: {
    name: "Watchtower",
    size: 3,
    cost: { wood: 45, stone: 20 },
    description: "A lookout above the trees. Expands your building boundary.",
    effect: "+3 tiles of buildable land",
    seconds: 16,
  },
  road: {
    name: "Path",
    size: 1,
    cost: { stone: 1 },
    description: "Connect your hamlet. Villagers move faster on paths.",
    effect: "+50% walking speed",
    seconds: 0,
  },
  flowerbed: {
    name: "Flower bed",
    size: 1,
    cost: { wood: 3 },
    description: "A little color for a path-side corner.",
    effect: "Decorative · does not block walking",
    seconds: 0,
    decoration: true,
  },
  bench: {
    name: "Bench",
    size: 1,
    cost: { wood: 6 },
    description: "A quiet seat where villagers can watch the day go by.",
    effect: "Decorative · does not block walking",
    seconds: 0,
    decoration: true,
  },
  sign: {
    name: "Sign",
    size: 1,
    cost: { wood: 5 },
    description: "Name a corner of the village with a handmade sign.",
    effect: "Decorative landmark · does not block walking",
    seconds: 0,
    decoration: true,
  },
};
