export const CATALOG = {
  house: {
    name: "Cottage",
    size: 3,
    cost: { wood: 30, stone: 10 },
    effect: "+2 housing capacity · villagers are trained at the School",
    seconds: 12,
  },
  well: {
    name: "Well",
    size: 2,
    cost: { wood: 15, stone: 25 },
    effect: "A gathering place for your village",
    seconds: 10,
  },
  farm: {
    name: "Farmhouse",
    size: 4,
    cost: { wood: 25, stone: 5 },
    effect: "Harvests ripe connected grain fields · +8 wheat per plot",
    resource: "wheat",
    amount: 8,
    outputCap: 16,
    seconds: 14,
    upgrade: {
      name: "Rich soil",
      cost: { wood: 35, stone: 12 },
      effect: "+4 wheat per harvest",
    },
  },
  bakery: {
    name: "Bakery",
    size: 3,
    cost: { wood: 40, stone: 25 },
    effect: "3 wheat → 5 bread per cycle · holds 5 bread until a carrier collects it",
    resource: "food",
    amount: 5,
    outputCap: 5,
    input: 3,
    inputResource: "wheat",
    seconds: 12,
  },
  inn: {
    name: "Inn",
    size: 4,
    cost: { wood: 55, stone: 25 },
    effect: "Holds 8 bread for 3 hungry villagers · overflow goes to a Storehouse",
    breadCap: 8,
    seconds: 18,
  },
  storehouse: {
    name: "Storehouse",
    size: 4,
    cost: { wood: 40, stone: 60 },
    effect: "+150 storage for every resource · posts 3 carriers",
    storage: 150,
    seconds: 24,
  },
  grainfield: {
    name: "Grain field",
    size: 1,
    cost: { food: 1 },
    effect: "Grows in 30 seconds · farmers harvest it automatically",
    seconds: 0,
    decoration: true,
    tileTool: true,
  },
  lumberyard: {
    name: "Lumberyard",
    size: 3,
    cost: { wood: 20, stone: 10 },
    effect: "+8 wooden planks per cycle · holds 16 until a carrier collects them",
    resource: "wood",
    amount: 8,
    outputCap: 16,
    seconds: 12,
  },
  mine: {
    name: "Stone mine",
    size: 4,
    cost: { wood: 35, stone: 15 },
    effect: "+6 stone per cycle · holds 12 until a carrier collects them",
    resource: "stone",
    amount: 6,
    outputCap: 12,
    seconds: 18,
  },
  windmill: {
    name: "Windmill",
    size: 4,
    cost: { wood: 50, stone: 35 },
    effect: "2 food → 8 food per cycle · holds 16 until a carrier collects it",
    resource: "food",
    amount: 8,
    outputCap: 16,
    input: 2,
    seconds: 20,
    upgrade: {
      name: "Faster sails",
      cost: { wood: 45, stone: 20 },
      effect: "Cycles 25% faster",
    },
  },
  watchtower: {
    name: "Watchtower",
    size: 3,
    cost: { wood: 45, stone: 20 },
    effect: "+3 tiles of buildable land",
    seconds: 16,
  },
  school: {
    name: "School",
    size: 4,
    cost: { wood: 60, stone: 45 },
    effect: "Trains builders and tradesfolk · 18 seconds each · needs housing room",
    trainSeconds: 18,
    seconds: 22,
  },
  vineyard: {
    name: "Vineyard",
    size: 4,
    cost: { wood: 45, stone: 30 },
    effect: "+6 wine per cycle · holds 12 until a carrier collects it",
    resource: "wine",
    amount: 6,
    outputCap: 12,
    seconds: 20,
  },
  road: {
    name: "Path",
    size: 1,
    cost: { stone: 1 },
    effect: "+50% walking speed · open ground slows villagers to 0.7x",
    seconds: 0,
  },
};

// The town hall is the village's first store, so a new settlement can trade
// before it can afford a Storehouse. Storehouses add their own capacity on top.
export const TOWNHALL_STORAGE = 200;
